CourseManagementSystem/CourseManagementSystem/Models/Course.cs
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration.Conventions;
using System.Linq;
using System.Web;

namespace CourseManagementSystem.Models
{
    public partial class Course
    {
        
        public int id { get; set; }

        [Display(Name = "Название")]
        public string name { get; set; }

        [Display(Name = "Описание")]
        public string description { get; set; }

        [Display(Name = "Дата публикации")]
        public System.DateTime PublishDate { get; set; }

        [Display(Name = "Оценка")]
        public Nullable<double> Estimation { get; set; }

        [Display(Name = "Количество оценок")]
        public Nullable<int> EstimationCount { get; set; }

        [Display(Name = "Категория")]
        public virtual Category Category { get; set; }

        [Display(Name = "Автор")]
        public virtual ApplicationUser Author { get; set; }

        [Display(Name = "Статус")]
        public bool activated { get; set; }
 


    }
    public partial class AddCourseModel
    {
        public AddCourseModel(Course course) 
        {
            id = course.id;
            name = course.name;
            description = course.description;
            category_id = course.Category.id;
        
        }

        public AddCourseModel()
        {

        }


        public int id { get; set; }

        [Display(Name = "Название")]
        public string name { get; set; }

        [Display(Name = "Описание")]
        public string description { get; set; }

        [Display(Name = "Категория")]
        public int category_id { get; set; }





    }


}

CourseManagementSystem/CourseManagementSystem/Models/Search.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CourseManagementSystem.Models
{
    public class Search
    {

        public string keywords { get; set; }

        public int category_id { get; set; }
    }
}

CourseManagementSystem/CourseManagementSystem/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Security.Claims;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;
using CourseManagementSystem.Models;

namespace CourseManagementSystem.Controllers
{
    public class CourseController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();

       
        // GET: /Course/
        public ActionResult List()
        {
            var course = db.Courses.Where(l => l.activated == true);
            return View(course.ToList());
        }


        [Authorize(Roles = "teacher")]
        public ActionResult Teacher()
        {

            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            string user = User.Identity.GetUserId();
            var course = db.Courses.Include(l => l.Author).Where(l => l.Author.Id == user);
            return View(course.ToList());
        }

        public ActionResult Search(Search search)
        {
            ViewBag.Keywords = search.keywords;
            ViewBag.Category = search.category_id;
            var course = db.Courses.Where(l => l.name.Contains(search.keywords)  && (search.category_id == 0 || l.Category.id == search.category_id));
            return View(course.ToList());
        }




        // GET: /Course/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        public ActionResult View(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // GET: /Course/Create

        [Authorize(Roles = "teacher")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Course/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.

        [Authorize(Roles = "teacher")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AddCourseModel courseview)
        {

            if (ModelState.IsValid)
            {

                var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
                var course = new Course() { name = courseview.name, description = courseview.description, Category = db.Categories.Find(courseview.category_id) };
                course.PublishDate = DateTime.Now;
                course.activated = false;
                course.Author = userManager.FindById(User.Identity.GetUserId());
                db.Courses.Add(course);
                db.SaveChanges();
                return RedirectToAction("Teacher");
            }

            return View(courseview);
        }

        // GET: /Course/Edit/5

        [Authorize(Roles = "teacher")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(new AddCourseModel(course));
        }

        // POST: /Course/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.

        [Authorize(Roles = "teacher")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AddCourseModel courseview)
        {
            if (ModelState.IsValid)
            {
                var course = db.Courses.Find(courseview.id);
                course.name = courseview.name;
                course.description = courseview.description;
                course.Category = db.Categories.Find(courseview.category_id);

                db.Entry(course).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Teacher");
            }
            return View(courseview);
        }

        // GET: /Course/Delete/5

        [Authorize(Roles = "teacher")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: /Course/Delete/5

        [Authorize(Roles = "teacher")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Course course = db.Courses.Find(id);
            db.Courses.Remove(course);
            db.SaveChanges();
            return RedirectToAction("Teacher");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CourseManagementSystem/CourseManagementSystem/Controllers/LecturesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CourseManagementSystem.Models;

namespace CourseManagementSystem.Controllers
{
    public class LecturesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private static int courseId;

        // GET: Lectures
        public ActionResult Index([Bind(Include = "id")] Course course)
        {
            courseId = course.id;
            ViewBag.CourseId = course.id;
            var lecture = db.Lecture.Include(l => l.Course).Where(l => l.Course.id == courseId);
            return PartialView(lecture.ToList());
        }

        public ActionResult EditList([Bind(Include = "id")] Course course)
        {
            courseId = course.id;
            var lecture = db.Lecture.Include(l => l.Course).Where(l => l.Course.id == courseId);
            return PartialView(lecture.ToList());
        }

        // GET: Lectures/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lecture lecture = db.Lecture.Find(id);
            if (lecture == null)
            {
                return HttpNotFound();
            }
            return View(lecture);
        }

        // GET: Lectures/Create
        public ActionResult Create()
        {
            ViewBag.CourseId = new SelectList(db.Courses, "id", "name");
            return View();
        }

		[HttpPost]
        public string Upload(IEnumerable<HttpPostedFileBase> fileUpload)
        {
            foreach (var file in fileUpload)
            {
                if (file == null) continue;
                string path = AppDomain.CurrentDomain.BaseDirectory + "resources/Media/";
                string filename = Path.GetFileName(file.FileName);
                if (filename != null)
                    try
                    {
                        file.SaveAs(Path.Combine(path, filename));
                    }
                    catch
                    {
                        return "File didn't loaded on server!";
                    }
            }

            return "";
        }
		
        // POST: Lectures/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "Id,CourseId,Name,Text,Number")] Lecture lecture)
        {
            if (ModelState.IsValid)
            {
                lecture.Course = db.Courses.Find(courseId);
                db.Lecture.Add(lecture);
                db.SaveChanges();
                return Redirect("/Course/Details/" + courseId);
            }

            ViewBag.CourseId = new SelectList(db.Courses, "id", "name", lecture.CourseId);
            return View(lecture);
        }

        // GET: Lectures/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lecture lecture = db.Lecture.Find(id);
            if (lecture == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseId = new SelectList(db.Courses, "id", "name", lecture.CourseId);
            return View(lecture);
        }

        // POST: Lectures/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "Id,CourseId,Name,Text,Number")] Lecture lecture)
        {
            if (ModelState.IsValid)
            {
                lecture.Course = db.Courses.Find(courseId);
                lecture.CourseId = courseId;
                db.Entry(lecture).State = EntityState.Modified;
                db.SaveChanges();
                return Redirect("/Course/Details/" + courseId);
            }
            ViewBag.CourseId = new SelectList(db.Courses, "id", "name", lecture.CourseId);
            return View(lecture);
        }

        // GET: Lectures/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lecture lecture = db.Lecture.Find(id);
            if (lecture == null)
            {
                return HttpNotFound();
            }
            return View(lecture);
        }

        // POST: Lectures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Lecture lecture = db.Lecture.Find(id);
            db.Lecture.Remove(lecture);
            db.SaveChanges();
            return Redirect("/Course/Details/" + courseId);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult RedirectToCourseView()
        {
            return Redirect("/Course/Details/" + courseId);
        }
    }
}

CourseManagementSystem/CourseManagementSystem/Views/Course/Create.cshtml
@using CourseManagementSystem.Models

@model AddCourseModel

@{
    ViewBag.Title = "Создать курс";
    var category = new ApplicationDbContext().Categories;
}

<h2>Создать курс</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Введите информацию о курсе</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.name, new { @class = " col-md-4" })
                @Html.ValidationMessageFor(model => model.name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.description, new { @class = "col-md-4" })
                @Html.ValidationMessageFor(model => model.description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.category_id, new { @class = "control-label col-md-2" })
            <div class="col-md-10"> 
                @Html.DropDownListFor(model => model.category_id, new SelectList(category, "id", "Name"), new { @class = "col-md-4" })
                @Html.ValidationMessageFor(model => model.category_id)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку", "Teacher")
</div>

CourseManagementSystem/CourseManagementSystem/Views/Course/Delete.cshtml
@model CourseManagementSystem.Models.Course

@{
    ViewBag.Title = "Delete";
}

<h2>Удалить курс</h2>

<h3>Вы действительно хотите удалить курс?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PublishDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PublishDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Вернуться", "Teacher")
        </div>
    }
</div>

CourseManagementSystem/CourseManagementSystem/Views/Course/Details.cshtml
@model CourseManagementSystem.Models.Course

@{
    ViewBag.Title = "Details";
}

<div class="col-md-4 " style="border-right:1px solid #eeeeee">
    <h2>О курсе</h2>

    <div style="padding-top:10px">
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PublishDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PublishDate)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.description)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Редактировать", "Edit", new { id = Model.id }) |
        @Html.ActionLink("Добавить тест", "CreateTest", "Tests", new { id = Model.id }, null) |
        @Html.ActionLink("Вернуться к списку", "Teacher")
    </p>
</div>
<div class="col-md-8">
    <p>
        @Html.Action("EditList", "Lectures", new { courceId = Model.id })
    </p>
</div>
<div class="col-md-9">

    <p>
        @Html.Action("EditList", "Tests", new { courseId = Model.id })
    </p>
</div>

CourseManagementSystem/CourseManagementSystem/Views/Course/Edit.cshtml
@using CourseManagementSystem.Models
@model AddCourseModel

@{
    ViewBag.Title = "Редактировать курс";
    var category = new ApplicationDbContext().Categories;
}

<h2>Редактирование курса</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Введите данные</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.name, new { @class = " col-md-4" })
                @Html.ValidationMessageFor(model => model.name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.description, new { @class = "col-md-4" })
                @Html.ValidationMessageFor(model => model.description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.category_id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.category_id, new SelectList(category, "id", "Name"), new { @class = "col-md-4" })
                @Html.ValidationMessageFor(model => model.category_id)
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку", "Teacher") | @Html.ActionLink("Назад к просмотру", "Details", new { id = Model.id })
</div>

CourseManagementSystem/CourseManagementSystem/Views/Course/List.cshtml
@using CourseManagementSystem.Models

@model IEnumerable<Course>

@{
    ViewBag.Title = "Курсы";
}

<h2>Курсы</h2>

@if (Model.Count() > 0) { 
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PublishDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Author)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PublishDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Author.FirstName)&nbsp;
            @Html.DisplayFor(modelItem => item.Author.LastName)
        </td>
        <td>
            @Html.ActionLink("Подробнее", "View", new { id=item.id })
        </td>
    </tr>
}

</table>
}
else
{
    
    <hr />
    <p style="color:#808080; text-align:center">
        У вас пока ещё нет курсов</p>
}

CourseManagementSystem/CourseManagementSystem/Views/Course/Search.cshtml
@using CourseManagementSystem.Models

@model IEnumerable<Course>

@{
    ViewBag.Title = "Результаты поиска";
    var category = new ApplicationDbContext().Categories;
    var list = new SelectList(category, "id", "Name");
}

<h2>Результаты поиска  </h2><h4>по запросу: "@ViewBag.Keywords"</h4><br />

<div class="list-group col-md-2">
    <div class="list-group-item" style="background-color:#c4c4c4"><h4 class="list-group-item-heading">Категории</h4></div>
    @if(ViewBag.Category == 0)
    {
    @Html.ActionLink("<Все>", "Search", "Course", new Search { category_id = 0, keywords = ViewBag.Keywords }, new { @class = "list-group-item active" })
    }
    else
    {
    @Html.ActionLink("<Все>", "Search", "Course", new Search { category_id = 0, keywords = ViewBag.Keywords }, new { @class = "list-group-item" })
    }
    @foreach(var item in category) 
    {
        if(item.id != ViewBag.Category)
        {
             @Html.ActionLink(item.Name, "Search", "Course", new Search { category_id = item.id, keywords = ViewBag.Keywords }, new { @class="list-group-item" })
        }
        else
        {
            @Html.ActionLink(item.Name, "Search", "Course", new Search { category_id = item.id, keywords = ViewBag.Keywords }, new { @class="list-group-item active" })
        }
}


</div>
@if (Model.Count() > 0)
{
    <div class="col-md-10">
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PublishDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Author)
        </th>
        <th></th>
    </tr>

            @foreach (var item in Model)
            {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PublishDate)
        </td>
        <td>
            @Html.ActionLink(Html.DisplayFor(modelItem => item.Author.FirstName).ToString() + " " + Html.DisplayFor(modelItem => item.Author.LastName).ToString(), "Usr", "Account", new { profile = item.Author.UserName }, null)
        </td>
        <td>
                        @Html.ActionLink("Подробнее", "View", new { id = item.id })
        </td>
    </tr>
}

</table>
    </div>
}
else
{
    
    <hr />
    <p style="color:#808080; text-align:center">
        Поиск не дал результатов</p>
}

CourseManagementSystem/CourseManagementSystem/Views/Course/Teacher.cshtml
@model IEnumerable<CourseManagementSystem.Models.Course>

@{
    ViewBag.Title = "Мои курсы";
}

<h2>Мои курсы</h2>

<p>
    @Html.ActionLink("Создать новый", "Create")
</p>
@if (Model.Count() > 0) { 
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PublishDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.activated)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PublishDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.activated)
        </td>
        <td>
            @Html.ActionLink("Подробнее", "Details", new { id=item.id }) |
            @Html.ActionLink("Удалить", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>
}
else
{
    
    <hr />
    <p style="color:#808080; text-align:center">
        У вас пока ещё нет курсов</p>
}

CourseManagementSystem/CourseManagementSystem/Views/Course/View.cshtml
@using CourseManagementSystem.Models
@model Course

@{
    ViewBag.Title = "Details";
}

<div class="col-md-4 " style="border-right:1px solid #eeeeee">
    <h2>О курсе</h2>

    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PublishDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PublishDate)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Author)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Author.FirstName)&nbsp;
                @Html.DisplayFor(model => model.Author.LastName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.description)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Вернуться к списку", "List")
    </p>

</div>

<div class="col-md-8">
    <p>

        @Html.Action("Index", "Lectures", new { courceId = Model.id })
    </p>
</div>
