CourseManagementSystem/CourseManagementSystem/Models/Test.cs
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration.Conventions;

namespace CourseManagementSystem.Models
{
    public partial class Test
    {

        public int Id { get; set; }
        public Test()
        {
            this.Question = new HashSet<Question>();
        }

        [Display(Name = "Имя лекции")]
        public int LastLectureId { get; set; }
        [Display(Name = "Номер")]
        public int Number { get; set; }

        public virtual Lecture Lecture { get; set; }
        public virtual ICollection<Question> Question { get; set; }
    }
}

CourseManagementSystem/CourseManagementSystem/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CourseManagementSystem.Models;

namespace CourseManagementSystem.Controllers
{
    public class QuestionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private static int testId;

        // GET: Questions
        public ActionResult Index()
        {
            return View(db.Question.ToList());
        }

        // GET: Questions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Question.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // GET: Questions/Create
        public ActionResult Create([Bind(Include = "Id")] Test test)
        {

            testId = test.Id;
            return View();
        }

        // POST: Questions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        // [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Text")] Question question, List<string> names, List<string> answers)
        {
            if (ModelState.IsValid)
            {
                question.Test = db.Test.Find(testId);
                
                db.Question.Add(question);
                for (int i = 0; i < 4; i++)
                {
                    bool b = false;
                    for (int j = 0; j < answers.Count; j++)
                    {
                        if (answers[j] == i.ToString())
                        {
                            b = true;
                        }
                    }
                    db.Answer.Add(new Answer() { IsTrue = b, Question = question, QuestionId = question.QuestionId, 
                        Text = names[i] });
                }
                db.SaveChanges();

                return RedirectToAction("QuestionsList", "Tests", new  { lectId= db.Test.Find(testId).Lecture.Id });
            }

            return View(question);
        }

        // GET: Questions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Question.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // POST: Questions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "QuestionId,Text")] Question question)
        {
            if (ModelState.IsValid)
            {
                db.Entry(question).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(question);
        }

        // GET: Questions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Question.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // POST: Questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Question question = db.Question.Find(id);
            Answer[] a = db.Answer.ToArray<Answer>();
            for (int i = 0; i < a.Count(); i++)
            {
                if (a[i].QuestionId == id)
                {
                    db.Answer.Remove(a[i]);
                }
            }
            db.SaveChanges();
            db.Question.Remove(question);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CourseManagementSystem/CourseManagementSystem/Controllers/TestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CourseManagementSystem.Models;
using System.Drawing;
using System.IO;

namespace CourseManagementSystem.Controllers
{
    public class TestsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Tests
        public ActionResult Index()
        {
            return View(db.Test.ToList());
        }

        private void PrintInPicture(Image inputImage)
        {
            using (System.Drawing.Graphics graphicsInputImage = Graphics.FromImage(inputImage))
            {
                graphicsInputImage.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.HighQuality;
                graphicsInputImage.CompositingQuality = System.Drawing.Drawing2D.CompositingQuality.HighQuality;
                graphicsInputImage.InterpolationMode = System.Drawing.Drawing2D.InterpolationMode.HighQualityBicubic;
                graphicsInputImage.CompositingMode = System.Drawing.Drawing2D.CompositingMode.SourceOver;
                graphicsInputImage.TextRenderingHint = System.Drawing.Text.TextRenderingHint.ClearTypeGridFit;
                graphicsInputImage.DrawString( "Моя крутая строка",new Font("Arial", 16), Brushes.Black,
                   new PointF(150.0F, 50.0F));
            }
        }

        public ActionResult Certificate()
        {
            Image im = Image.FromFile("C:\\Users\\Андрей\\Documents\\GitHub\\Course-Management-System\\CourseManagementSystem\\CourseManagementSystem\\Views\\Tests\\p.jpg");
            
            PrintInPicture(im);
            return View();
        }


        public ActionResult QuestionsList(int lectId)
        {

            if (!(db.Question.Count() > 0) && !(db.Test.Count() > 0))
            {
                return View();
            }
            var t = db.Test.Where(l => l.Lecture.Id == lectId).ToList();
            ViewBag.TestId = t[0].Id;

            int tk = t[0].Id;

            var questions = (db.Question.Where(l => l.Test.Id == tk)).ToArray<Question>().ToList<Question>();
            ViewBag.Questions = questions;

            return View();
        }

        // GET: Tests/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Test test = db.Test.Find(id);
            if (test == null)
            {
                return HttpNotFound();
            }
            return View(test);
        }
        public ActionResult EditList(int courseId)
        {
            List<Test> tests = new List<Test>();
            List<Lecture> c = new List<Lecture>();

            foreach (var t in db.Test.ToList())
            {
                if (t.Lecture.CourseId == courseId)
                {
                    tests.Add(t);
                    c.Add(t.Lecture);
                }
            }

            ViewBag.Lectures = c;

            return View(tests);
        }
        // GET: Tests/CreateTest
        public ActionResult CreateTest(int id)
        {
            List<Lecture> q = db.Lecture.ToList();
            List<SelectListItem> lects = new List<SelectListItem>();

            foreach (var i in q)
            {
                if (i.CourseId == id)
                    lects.Add(new SelectListItem { Text = i.Name });
            }

            ViewBag.Lectures = lects;
            return View();
        }



        // POST: Tests/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateTest([Bind(Include = "Id")] Test test, string lectureName, int id)
        {
            if (ModelState.IsValid)
            {
                List<Lecture> q = db.Lecture.ToList();
                Lecture neededLect = new Lecture();

                foreach (var i in q)
                {
                    if (i.CourseId == id && i.Name == lectureName)
                    {
                        foreach (var c in db.Test.ToList())
                        {
                            if (c.Lecture.Id == i.Id)
                            {
                                return RedirectToAction("CreateTest", "Tests", new Course { id = id });
                            }
                        }
                        test.Lecture = i;
                        test.LastLectureId = i.Id;
                    }
                }

                db.Test.Add(test);
                db.SaveChanges();
                return RedirectToAction("Details", "Course", new Course { id = id });
            }

            return View(test);
        }

        // GET: Tests/Create
        public ActionResult Create()
        {

            return View();
        }

        // POST: Tests/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,LastLectureId,Number")] Test test)
        {
            if (ModelState.IsValid)
            {
                db.Test.Add(test);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(test);
        }

        // GET: Tests/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Test test = db.Test.Find(id);

            if (test == null)
            {
                return HttpNotFound();
            }
            return View(test);
        }

        // POST: Tests/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,LastLectureId,Number")] Test test)
        {
            if (ModelState.IsValid)
            {
                db.Entry(test).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(test);
        }

        // GET: Tests/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            Test test = db.Test.Find(id);
            if (test == null)
            {
                return HttpNotFound();
            }
            return View(test);
        }

        // POST: Tests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Test test = db.Test.Find(id);
            Question[] q = db.Question.ToArray<Question>();
            for (int i = 0; i < q.Count(); i++)
            {
                if (q[i].Test.Id == id)
                {
                    deleteAnswers(q[i].QuestionId, q[i]);
                }
            }
            db.SaveChanges();
            db.Test.Remove(test);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        private void deleteAnswers(int id, Question question)
        {
            Answer[] a = db.Answer.ToArray<Answer>();
            for (int i = 0; i < a.Count(); i++)
            {
                if (a[i].QuestionId == id)
                {
                    db.Answer.Remove(a[i]);
                }
            }
            db.SaveChanges();
            db.Question.Remove(question);
            db.SaveChanges();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CourseManagementSystem/CourseManagementSystem/Views/Tests/Certificate.cshtml
@{
    ViewBag.Title = "Certificate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Certificate</h2>

CourseManagementSystem/CourseManagementSystem/Views/Tests/Create.cshtml
@model CourseManagementSystem.Models.Test

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Test</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.LastLectureId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastLectureId)
                @Html.ValidationMessageFor(model => model.LastLectureId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number)
                @Html.ValidationMessageFor(model => model.Number)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CourseManagementSystem/CourseManagementSystem/Views/Tests/CreateTest.cshtml
@model CourseManagementSystem.Models.Test


@{
    ViewBag.Title = "CreateTest";
    List<SelectListItem> lecturesNames = ViewBag.Lectures;
    string w = ViewBag.Warning;
}

<h2>CreateTest</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Test</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.LastLectureId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("lectureName", lecturesNames)

                @Html.ValidationMessageFor(model => model.LastLectureId)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="CreateTest" class="btn btn-default" />
            </div>
        </div>
    </div>
}

CourseManagementSystem/CourseManagementSystem/Views/Tests/Delete.cshtml
@model CourseManagementSystem.Models.Test

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Test</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LastLectureId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastLectureId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CourseManagementSystem/CourseManagementSystem/Views/Tests/Details.cshtml
@model CourseManagementSystem.Models.Test

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Test</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LastLectureId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastLectureId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>

    </dl>
</div>



<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CourseManagementSystem/CourseManagementSystem/Views/Tests/Edit.cshtml
@model CourseManagementSystem.Models.Test

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Test</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.LastLectureId, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.EditorFor(model => model.LastLectureId)
                @Html.ValidationMessageFor(model => model.LastLectureId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number)
                @Html.ValidationMessageFor(model => model.Number)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<hr />
@Html.LabelFor(model => model.Question)<br />
<div class="col-md-10">
</div>
<hr />
<div>
    <h3>
        @Html.ActionLink("Добавить вопрос", "Create", "Questions", new { Id = Model.Id }, null)
    </h3><br />
    @Html.ActionLink("Back to List", "Index")
</div>
<hr />

CourseManagementSystem/CourseManagementSystem/Views/Tests/EditList.cshtml
@{
    ViewBag.Title = "Список тестов";
    List<CourseManagementSystem.Models.Lecture> lects = ViewBag.Lectures;
    int testId = 0;
}

@model IEnumerable<CourseManagementSystem.Models.Test>

<h2>Тесты</h2>
<h4>Имя лекции</h4>
@if (Model.Count() > 0)
{
    <table class="table">
        @foreach (var item in lects)
        {
            foreach (var i in Model)
            {
                if (i.Lecture == item)
                {
                    testId = i.Id;
                }
            }
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)

                </td>
                <td>
                    @Html.ActionLink("Подробнее", "QuestionsList", new { lectId = item.Id }) |



                    @Html.ActionLink("Удалить", "Delete", new { id = testId })
                </td>
            </tr>
        }

    </table>
}
else
{
    <hr />
    <p style="color:#808080; text-align:left">
        Здесь пока ещё нет тестов
    </p>
}

CourseManagementSystem/CourseManagementSystem/Views/Tests/Index.cshtml
@model IEnumerable<CourseManagementSystem.Models.Test>

@{
    ViewBag.Title = "Index";
   
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.LastLectureId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Number)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.LastLectureId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Number)
        </td>
        <td>
            @Html.ActionLink("Редактировать", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Просмотр", "Details", new { id=item.Id }) |
            @Html.ActionLink("Удалить", "Delete", new { id=item.Id }) |
        </td>
    </tr>
   
}
 

</table>

CourseManagementSystem/CourseManagementSystem/Views/Tests/QuestionsList.cshtml
@{
    ViewBag.Title = "QuestionsList";
    List<CourseManagementSystem.Models.Question> questions = ViewBag.Questions;
    //   List<CourseManagementSystem.Models.Answer> answers = ViewBag.AnswersToList;
    int answersCount = 4;
    int currQuest = 0;
    int testId = ViewBag.TestId;
}

<h2>QuestionsList</h2>

@model IEnumerable<CourseManagementSystem.Models.Test>


<table class="table">
    <tr>
        <td>
            <h4>Текст вопроса</h4>
        </td>
        <td>
            <h4>Варианты ответа</h4>
        </td>
    </tr>

</table>

@if (questions.Count() > 0)
{
    <table class="table">
        @foreach (var item in questions)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Text)

                </td>
                <td>
                    @for (int i = 0; i < answersCount; i++)
                    {
                        <br />
                        @Html.DisplayFor(modelItem => questions[currQuest].Answer.ToList().ElementAt(i).Text) 
                    }
                    @{ currQuest++; }
                </td>
            </tr>
        }

    </table>
}
else
{
    <hr />
    <p style="color:#808080; text-align:left">
        Здесь пока ещё нет вопросов
    </p>
}

<div class="col-md-9">

    <p>
        @Html.ActionLink("Добавить вопрос", "Create", "Questions", new { Id = testId }, null)
    </p>
</div>

<div class="col-md-9">

    <p>
        @Html.ActionLink("Добавить вопрос", "Create", "Questions", new { Id = testId }, null)
    </p>
</div>