CourseManagementSystem/CourseManagementSystem/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Security.Claims;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;
using CourseManagementSystem.Models;

namespace CourseManagementSystem.Controllers
{
    public class CourseController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();

       
        // GET: /Course/
        public ActionResult List()
        {
            var course = db.Courses.Where(l => l.activated == true);
            return View(course.ToList());
        }


        [Authorize(Roles = "teacher")]
        public ActionResult Teacher()
        {

            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            string user = User.Identity.GetUserId();
            var course = db.Courses.Include(l => l.Author).Where(l => l.Author.Id == user);
            return View(course.ToList());
        }

        public ActionResult Search(Search search)
        {
            ViewBag.Keywords = search.keywords;
            ViewBag.Category = search.category_id;
            var course = db.Courses.Where(l => l.name.Contains(search.keywords)  && (search.category_id == 0 || l.Category.id == search.category_id));
            return View(course.ToList());
        }




        // GET: /Course/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        public ActionResult View(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // GET: /Course/Create

        [Authorize(Roles = "teacher")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Course/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.

        [Authorize(Roles = "teacher")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AddCourseModel courseview)
        {

            if (ModelState.IsValid)
            {

                var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
                var course = new Course() { name = courseview.name, description = courseview.description, Category = db.Categories.Find(courseview.category_id) };
                course.PublishDate = DateTime.Now;
                course.activated = false;
                course.Author = userManager.FindById(User.Identity.GetUserId());
                db.Courses.Add(course);
                db.SaveChanges();
                return RedirectToAction("Teacher");
            }

            return View(courseview);
        }

        // GET: /Course/Edit/5

        [Authorize(Roles = "teacher")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(new AddCourseModel(course));
        }

        // POST: /Course/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.

        [Authorize(Roles = "teacher")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AddCourseModel courseview)
        {
            if (ModelState.IsValid)
            {
                var course = db.Courses.Find(courseview.id);
                course.name = courseview.name;
                course.description = courseview.description;
                course.Category = db.Categories.Find(courseview.category_id);

                db.Entry(course).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Teacher");
            }
            return View(courseview);
        }

        // GET: /Course/Delete/5

        [Authorize(Roles = "teacher")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: /Course/Delete/5

        [Authorize(Roles = "teacher")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Course course = db.Courses.Find(id);
            db.Courses.Remove(course);
            db.SaveChanges();
            return RedirectToAction("Teacher");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CourseManagementSystem/CourseManagementSystem/Controllers/MarkController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Runtime.InteropServices;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using CourseManagementSystem.Models;

namespace CourseManagementSystem.Controllers
{
    public class MarkController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Marks
        [Authorize(Roles = "student")]
        public ActionResult Student()
        {
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            string user = User.Identity.GetUserId();
            var course = db.Subscription.Include(l => l.Subscriber).Where(l => l.Subscriber.Id == user);
            //var mark = db.Mark.Include(l => l.Student).Where(l => l.Student.Id == user);
            return View(course.ToList());
        }

        public ActionResult Details(int id)
        {
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            string user = User.Identity.GetUserId();
            var mark = db.Mark.Include(l => l.Subscription.Subscriber).Where(l => l.Subscription.Subscriber.Id == user && l.Subscription.Course.id == id);

            var lecture = (db.Lecture.Where(l => l.CourseId == id)).ToList<Lecture>();
            ViewBag.Lectures = lecture;
            return View(mark.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CourseManagementSystem/CourseManagementSystem/Views/Shared/_Layout.cshtml

<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body style=" padding-bottom: 70px;">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                @Html.ActionLink("Course Management System", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Все курсы", "List", "Course")</li>
                </ul>
                @if (User.IsInRole("teacher")) { 
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("Мои курсы", "Teacher", "Course")</li>
                </ul>
                 }
                @if (User.IsInRole("student"))
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Мои курсы", "Student", "Mark")</li>
                    </ul>
                }
                @Html.Partial("_LoginPartial")
                @Html.Partial("_SearchPartial", new CourseManagementSystem.Models.Search())
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <nav class="navbar navbar-default navbar-fixed-bottom" role="navigation" style="background-color:#222222; border-bottom:none;">
            <footer class="container-fluid" style="text-align:center;color:#ffffff;">
                <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
            </footer>
        </nav>
     </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CourseManagementSystem/CourseManagementSystem/Views/Shared/_SearchPartial.cshtml
@using CourseManagementSystem.Models
@model Search
@{
    var category = new ApplicationDbContext().Categories;
    Model.category_id = 0;
}
@using (Html.BeginForm("Search", "Course", Model, FormMethod.Post))
{
    <ul class="nav navbar-nav pull-right" style="background-color: #393939; height: 50px; padding: 12px 0px 0px 15px">
       <li> @Html.TextBoxFor(model => model.keywords, new { @class = "input-medium search-query", placeholder = "Поиск"})</li>
        <li><input type="submit" value="Найти" class="btn-link"/>})</li>
    </ul>
}